name: 'Puppeteer URL to PDF action'
description: 'Create a PDF from URL using puppeteer'
inputs:
  url:
    required: true  
    description: 'The URL'
  output-file-path:
    required: true
    description: 'The path to write the PDF file to'  
    default: 'output.pdf'
  page-ranges:
    required: false
    description: 'Paper ranges to print, e.g. 1-5, 8, 11-13'
  format:
    required: false
    description: 'Sets the width of paper. You can pass in a number or a string with a unit.'
  margin:
    required: false
    description: 'Set the PDF margins. If set, it overrides the values of individual margins.'
  left-margin:
    required: false
    description: 'PDF left margin'
  right-margin:
    required: false
    description: 'PDF right margin'
  top-margin:
    required: false
    description: 'PDF top margin'
  bottom-margin:
    required: false
    description: 'PDF bottom margin'
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: 'message-square'  
  color: 'gray-dark'